/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moqucu.akka;

import lombok.extern.log4j.Log4j2;

@Log4j2
public class App {
    public String getGreeting() {

        return "Hello World!";
    }

    public static void main(String[] args) {

        log.info(new App().getGreeting());
     }
}
